### PR TITLE
update Vietnamese translation

### PR DESCRIPTION
**Pull request by cuongdcdev**

### CODE REVIEW

**Review by ahnafalfariza — COMMENTED** [review]
Hi could you please resolve the conflict? You can pull from the main branch and merge to your branch.

**Comment by cuongdcdev** [comment]
@ahnafalfariza conflicts resolved, plz check ^^

**Comment by ahnafalfariza** [comment]
Hi @cuongdcdev are you intendedly closing this PR?

**Comment by cuongdcdev** [comment]
@ahnafalfariza oops, my fault, re-opened

**Review by ahnafalfariza — APPROVED** [review]

**Pull request merged**
